fmod MYINT is
  sort Int .
  op 0 : -> Int .
  op s_ : Int -> Int .
  op p_ : Int -> Int .
  op _+_ : Int Int -> Int [assoc comm prec 33].
  op _-_ : Int Int -> Int [assoc comm prec 33].
  op _*_ : Int Int -> Int [assoc comm prec 31].
  
  vars N M : Int .
  
  eq 0 + M = M .
  eq M - 0 = M .
  eq 0 * M = 0 .
  
  eq s(N) + M = s(N + M) .
  eq s(N) * M = (N * M) + M .
  eq N - s(M) = p(N - M) .
  
  eq p(N) + M = p(M + N) .
  eq p(N) * M = (N * M) - M .
  eq M - p(N) = s(M - N) .
  
  eq s p N = N .
  eq p s N = N .
endfm

red p(0) + s(0).
red s(0) * s(0) + p(0) .
red s(s(s(p(0)))) .
red s(0) + s(0) - s(0) .
red (s(0) + s(0) - s(0)) + p(0) .