fmod MYMOD is
  including INT .
  
  op aduna_ _ : Int Int -> Int .
  op scade_ _ : Int Int -> Int .
  op inmulteste_ _ : Int Int -> Int .
  op imparteCat_ _ : Int Int -> Int .
  op imparteRest_ _ : Int Int -> Int .
  
  vars A B : Int .
  
  eq aduna A B = A + B .
  eq scade A B = A - B .
  eq inmulteste A B = A * B .
  eq imparteCat A B = A quo B .
  eq imparteRest A B = A rem B .

endfm

red aduna 7 3 .
red scade 15 5 .
red inmulteste 2 5 .
red imparteCat 3 2 .
red imparteRest 3 2 .