fmod MYINT is

sort Int .

op 0 : -> Int .

op s_ : Int -> Int .

op p_ : Int -> Int .

op _+_ : Int Int -> Int .

op _-_ : Int Int -> Int .

op _*_ : Int Int -> Int .

vars N, M : Int .
  
eq 0 + M = M .
  
eq 0 * M = 0 .
  
eq M - 0 = M .

eq s(N) + M = s(N + M) .

eq s(N) * M = (N * M) + M .
  
eq N - s(M) = p(N - M) .
  
eq p(N) + M = p(N + M) .
  
eq p(N) * M = (N * M) - M .
  
eq N - p(M) = s(N - M) .
  
eq s p N = N .
  
eq p s N = N .

endfm

